# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-08 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptomodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
